{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "E   assert False"}, "description": "Test que prueba otra cosa", "start": 1652975534642, "stop": 1652975534642, "uuid": "8b84c9b7-df0c-4d2c-8a6e-fc79daa00208", "historyId": "de7f32baed47619a4a1b82e3e0fbc334", "testCaseId": "6c04b0da6552e3cc4d5c748b0b7dc318", "fullName": "tests.test_10_allure.TestReports#test_3", "labels": [{"name": "severity", "value": "minor"}, {"name": "tag", "value": "cashin"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_10_allure"}, {"name": "subSuite", "value": "TestReports"}, {"name": "host", "value": "WKSAR1848L.local"}, {"name": "thread", "value": "5519-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_10_allure"}]}